[package]
name = "energy-reader"
version = "0.1.0"
edition = "2024"

[features]
debug_img = []

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
rustfft = "6.4.1"